//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbFacturaDetalle
    {
        [Key]
        public int fadId { get; set; }
        public int faId { get; set; }
        public int fadProducto { get; set; }
        public decimal fadPrecioVenta { get; set; }
        public int fadCantidad { get; set; }
            
    }
}
