//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFacturaEncabezado
    {    
        public int faId { get; set; }
        public string faNumero { get; set; }
        public decimal faImpuesto { get; set; }
        public string faUsuario { get; set; }
        public System.DateTime faFecha { get; set; }
        public int faIdCliente { get; set; }
        public int faIdEmpresa { get; set; }
    
    }
}
